/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/404PageBitcoin.glb -t 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { RefObject, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { Group } from 'three';

type GLTFResult = GLTF & {
	nodes: {
		Plane: THREE.Mesh;
		Cylinder_1: THREE.Mesh;
		Cylinder_2: THREE.Mesh;
		Curve: THREE.Mesh;
		Curve001: THREE.Mesh;
	};
	materials: {
		['gold main']: THREE.MeshStandardMaterial;
		['gold img']: THREE.MeshStandardMaterial;
	};
	// animations: GLTFAction[];
};

// type ContextType = Record<
// 	string,
// 	React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
// >;

export function Bitcoin(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'./models/404PageBitcoin.glb'
	) as GLTFResult;
	const BtcRef: RefObject<Group> = useRef<Group>(null);

	useFrame((state) => {
		if (BtcRef.current) {
			BtcRef.current.rotation.y += Math.cos(state.clock.elapsedTime * 0.5) / 30;
			// BtcRef.current.position.y += Math.sin(state.clock.elapsedTime) / 100;
			// BtcRef.current.rotation.z += Math.cos(state.clock.elapsedTime) / 200;
		}
	});
	return (
		<group ref={BtcRef} {...props} dispose={null}>
			<group
				position={[0, 5.674, 0]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[5, 0.5, 5]}
			>
				<mesh
					geometry={nodes.Cylinder_1.geometry}
					material={materials['gold main']}
				/>
				<mesh
					geometry={nodes.Cylinder_2.geometry}
					material={materials['gold main']}
				/>
			</group>
			<mesh
				geometry={nodes.Curve.geometry}
				material={materials['gold img']}
				position={[0, 5.674, 0.274]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[58.803, 1, 58.803]}
			/>
			<mesh
				geometry={nodes.Curve001.geometry}
				material={materials['gold img']}
				position={[0, 5.674, -0.27]}
				rotation={[Math.PI / 2, 0, Math.PI]}
				scale={[58.803, 1, 58.803]}
			/>
		</group>
	);
}

useGLTF.preload('./models/404PageBitcoin.glb');
