/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/btc.glb 
Author: deaconskywalker9 (https://sketchfab.com/deaconskywalker9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pixel-art-bitcoin-3d-model-bfe05c4499044f0e93a7d987107bddfc
Title: Pixel Art Bitcoin 3D Model
*/

import { useGLTF } from '@react-three/drei';
import { Group, Mesh } from 'three';

interface Nodes {
	[key: string]: Mesh | Group | undefined;
}

export function Btc() {
	const { nodes, materials } = useGLTF('./models/btc.glb');

	const typedNodes = nodes as Nodes;

	return (
		<group dispose={null}>
			<group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group rotation={[0, 0, -Math.PI / 2]} scale={2}>
						<mesh
							geometry={(typedNodes.Object_4 as Mesh)?.geometry}
							material={materials['.004']}
						/>
						<mesh
							geometry={(typedNodes.Object_5 as Mesh)?.geometry}
							material={materials['.005']}
						/>
						<mesh
							geometry={(typedNodes.Object_6 as Mesh)?.geometry}
							material={materials['.006']}
						/>
						<mesh
							geometry={(typedNodes.Object_7 as Mesh)?.geometry}
							material={materials['.007']}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('./models/btc.glb');
